#!/bin/bash
ls -a | grep -E '^(\.|\.\.)$' | tr '\n' ',' | sed 's/,$//' && ls -a | grep -vE '^(\.|\.\.)$' | sed 's/$/,/' | sed 's/^\(.*\)/\L\1/' | sort -t '' -k 1.1n -k 1.2,1 | sed 's/,$//' | tr '\n' ',' | sed 's/\(.*\),/\1\n/'
